---
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: "bundle exec rake syntax:hiera"
matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
    - rvm: 2.0.0
notifications:
  email: false
